version: '3.4'

services:
  demo.apis.bacon:
    ports:
      - "80"

  demo.microservices.api.docs:
    ports:
      - "889:80"

  demo.microservices.gateway:
    env_file:
      - api-gateway.conf
    ports:
      - "888:8080"
